trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:

  # Azure
  azureSubscription: azure-service-connection

stages:

- stage: test

  jobs:
  - job: tests
    pool: Hosted Ubuntu 1604
    continueOnError: false
    timeoutInMinutes: 20

    steps:

    # Temp test, replace this with ARM TTK / Python Test Suite?
    - task: PowerShell@2
      displayName: Install Pester
      inputs:
        targetType: 'inline'
        script: |
          Find-Module pester | Install-Module -Force

- stage: build
  dependsOn: test
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  jobs:
  - job: helm
    pool: Hosted Ubuntu 1604
    continueOnError: false
    timeoutInMinutes: 20

- stage: infrastructure_pre_production
  dependsOn: build

  jobs:
  - job: arm
    pool: Hosted Ubuntu 1604
    continueOnError: false

    steps:

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'azure-service-connection'
        subscriptionId: '10a09851-d632-420e-ad20-2cd774fd4d41'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'test123'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: './deployment/arm/azuredeploy.json'
        csmParametersFile: './deployment/arm/azuredeploy.parameters.json'
        deploymentMode: 'Incremental'

# - stage: app_pre_production
#   dependsOn: infrastructure_pre_production

# - stage: infrastructure_pre_production
#   dependsOn: build

# - stage: app_pre_production
#   dependsOn: infrastructure_pre_production
