trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'twitter-app'

  # # Azure
  # azureSubscription: azure-service-connection

  # # Container Registry
  # AZURE_CONTAINER_REGISTRY: nepetersacr008
  # AZURE_CONTAINER_REGISTRY_FQDN: nepetersacr008.azurecr.io
  # AZURE_MANAGED_IDENTITY_NAME: ninernep001
  # AZURE_KUBERNETES_SERVICE: ninernep003
  # AZURE_STORAGE_ACCT: ninernep004
  # AZURE_RESOURCE_GROUP: ninernep005
  # AZURE_COSMOS_DB: ninernep006
  # AZURE_ANALYTICS: ninernep007

stages:

- stage: test

  jobs:
  - job: tests
    pool: Hosted Ubuntu 1604
    continueOnError: false
    timeoutInMinutes: 20

    steps:

    # Temp test, replace this with ARM TTK / Python Test Suite?
    - task: PowerShell@2
      displayName: Install Pester
      inputs:
        targetType: 'inline'
        script: |
          Find-Module pester | Install-Module -Force

- stage: infrastructure_pre_production
  # dependsOn: build

  jobs:
  - job: arm
    pool: Hosted Ubuntu 1604
    continueOnError: false

    steps:

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureSubscription)'
        subscriptionId: '10a09851-d632-420e-ad20-2cd774fd4d41'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(AZURE_RESOURCE_GROUP)'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: './deployment/arm/azuredeploy.json'
        # csmParametersFile: './deployment/arm/azuredeploy.parameters.json'
        overrideParameters: '-aksName "$(AZURE_KUBERNETES_SERVICE)" -storageAccountName "$(AZURE_STORAGE_ACCT)" -cognitiveName "$(AZURE_ANALYTICS)" -scriptIdentity "$(AZURE_MANAGED_IDENTITY_NAME)" -cosmosName "$(AZURE_COSMOS_DB)" -acrName "$(AZURE_CONTAINER_REGISTRY)"'
        deploymentMode: 'Incremental'
