apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chart-tweet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chart-tweet
    spec:
      containers:
      - name: chart-tweet
        image: neilpeterson/chart-tweet
        env:
        - name: COSMOS_DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: uri
              name: tweet-scope-cosmos
        - name: COSMOS_DB_MASTERKEY
          valueFrom:
            secretKeyRef:
              key: primaryKey
              name: tweet-scope-cosmos
        - name:  COSMOS_DB_DATABASE
          value: mytwittersentiment
        - name:  COSMOS_DB_COLLECTION
          value: mytwittersentiment
        - name:  CHART_LABEL
          value: "Tweets about Azure"
---
apiVersion: v1
kind: Service
metadata:
  name: chart-tweet
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: chart-tweet